### ISSUE TITLE
App Crashes On Clicking Send When There are no forms inside

### ISSUE THREAD

**Issue by iadeelzafar** [opendatakit/share#100]
### Summary:
App Crashes On Clicking Send When There are no forms inside

### To Reproduce:
1- Install collect
2- Don't import any form, just go to Share and click on SEND.

I'd like to work on this issue. Suggestions are welcomed on how this issue could be resolved.

### Screenshot:
<img src="https://user-images.githubusercontent.com/36811908/52628624-dfdb8f80-2ed9-11e9-949a-8c783287888d.gif" height="700" width="394">

**Comment by shobhitagarwal1612** [comment]
I guess SEND button shouldn't be enabled at all if no forms are available
@lakshyagupta21 any thoughts?

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 correct it shouldn't be enabled.
Expected behavior - `send` button should be disabled as well as there should be some empty view message on the screen.

**Comment by iadeelzafar** [comment]
@lakshyagupta21 I opened an issue before about the empty view too.

**Comment by iadeelzafar** [comment]
@opendatakit-bot claim
