### ISSUE TITLE
Disable SCAN QR BUTTON when WIFI is not available

### ISSUE THREAD

**Issue by iadeelzafar** [opendatakit/share#101]
### Summary
Disable SCAN QR BUTTON when WIFI is not available

### To Reproduce:
* Go to Receive Button
* Wait for WIFI to scan.
* If no WIFI is available, SCAN QR Button is still enable.

I'd like to work on this issue.

### Screenshots:
<img src="https://user-images.githubusercontent.com/36811908/52629197-f9310b80-2eda-11e9-9aa7-442169c0c578.gif" height="700" width="394">

**Comment by shobhitagarwal1612** [comment]
Thanks for filing an issue and volunteering to work on it.
Please claim the issue by commenting `@opendatakit-bot claim`

**Comment by lakshyagupta21** [comment]
Sometimes the device is not able to detect wifi networks that fast.
`Scan QR Code` button just scans the QR code displayed in someone else's device and if that device wifi is in range it will connect. Its similar to 'SCAN WIFI' button but it does one step more that is device connection.

**Comment by iadeelzafar** [comment]
@opendatakit-bot claim

**Comment by iadeelzafar** [comment]
@lakshyagupta21 got it. It means this button must be enabled all the time.

**Comment by shobhitagarwal1612** [comment]
I think we can close the issue now.
Please reopen if you still think it is a better idea to disable the button
