### ISSUE TITLE
Establish socket connection over wifi-hotspot

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/share#11]

**Comment by lakshyagupta21** [comment]
Which method would be more preferred for sharing forms with only one enumerators or with multiple enumerators ?

**Comment by lognaturel** [comment]
Good question. It feels simpler to always send the blank form and do the check on the receiving end. Sending an extra file doesn't seem like it's a big deal since we know the connection will be very fast. I can't currently think of any downsides of doing it this way, can you?

**Comment by lakshyagupta21** [comment]
I agree as the connection is fast, sending a form won't take much time as compared to instances.

**Comment by shobhitagarwal1612** [comment]
> Sending an extra file

if the checks are happening at the receiving end then the media files should also be sent which can be a lot in number

**Comment by lognaturel** [comment]
That's a very good point, @shobhitagarwal1612. Given that it's a local wifi connection, I think we can expect at very worst 5mbps so I think we're talking about at most a couple of extra seconds. Still, for forms that have videos or lots of images it could be a problem. How about going with the simple approach for now and filing an issue to get feedback and maybe consider alternatives?

One other option might be a hybrid of what @lakshyagupta21 was suggesting -- something like send the form, if there's no media, send the instances but if there is media, wait to hear back from the receiver whether the media is needed.
