### ISSUE TITLE
Hotspot Connection TextView Should Be Centered

### ISSUE THREAD

**Issue by iadeelzafar** [opendatakit/share#125]
### Describe the issue:
The hospot connection info textview is right below the toolbar which isn't very pleasant.

### Expected Behaviour:
The hospot connection info textview should be centered vertically and horizontally.

### Screenshot:
<img src="https://user-images.githubusercontent.com/36811908/53493656-af8d1700-3abd-11e9-84c5-cfc34eab6a32.gif" height="700" width="394">

**Comment by lakshyagupta21** [comment]
@iadeelzafar I don't think this is required, because if you add it to the center dialog box will hide the text and for some devices, QR Code will be shown directly in the center without dialog box, so indentation of text view looks fine.

**Comment by iadeelzafar** [comment]
Thanks for reviewing. Got your point. This can be closed now.
