### ISSUE TITLE
Setting up CI

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#2]

**Comment by lognaturel** [comment]
@shobhitagarwal1612 @yanokwa Should this go straight to using the ODK account or should @lakshyagupta21 use his own account for now? If you think it should use the ODK account, please give @lakshyagupta21 access, @yanokwa

**Comment by yanokwa** [comment]
I think this can be built on the ODK account. I think all that has to happen is adding basic CircleCI config like Collect has. https://github.com/opendatakit/collect/blob/master/.circleci/config.yml is a good place to start. Maybe comment out the instrumented tests for now if that requires GCloud access.
