### ISSUE TITLE
Create database and save information received from the receiver end

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/share#26]
* Create share db for storing send/receive data
* Store instance information in instance db
* Store instance information share db

**Comment by lakshyagupta21** [comment]
For all form/instance transfer, I'm thinking of creating different table `share` which will save data related to the file transfer like `sent/received, instanceId, formStatus, lastStatusChangeDate`. Here `instanceId` is a foreign key referencing `instance` table which is in `instance.db`. 

And I think it is not possible to add foreign key referencing table in a different database. 

I can think of two solutions
1. Create `share` table in `instance.db` but this has to be done in Collect code.
2. Other option I came across by searching on internet is using triggers or functions.

**Comment by lognaturel** [comment]
Can it be kind of an informal foreign key? That is, can you store the key and then use it to query the instance.db explicitly rather than through a join?
