### ISSUE TITLE
Handle cancel event of Async Tasks

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/share#31]
Noticed in PR #25 
Not able to send/receive forms if a user tries again after an activity is destroyed by pressing back button or cancel button of a progress bar.

New Async task won't start until the previous one gets finished. So need to handle the cancelling event of Async tasks.

**Comment by lakshyagupta21** [comment]
Thanks @lognaturel and @shobhitagarwal1612 !!

**Comment by lognaturel** [comment]
Hurray, glad you tracked it down!! 🎉
