### ISSUE TITLE
Main Screen to show all the forms available

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/share#32]
1. Show all the forms available in device.
2. Tapping on any category will open a activity which will show instances of that category only.
3. Add send and receive buttons to send the forms (Activity will show all the instances of all the forms)

![3](https://user-images.githubusercontent.com/18495162/41501994-ea52587e-71cc-11e8-9aed-6b3dee5058dd.PNG)

**Comment by lognaturel** [comment]
I believe this can now be closed! 🎉
