### ISSUE TITLE
Screen for showing stats, sent, received, review forms

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/share#37]
Create screen with tabs that show  statistics, sent forms, received forms, reviewed forms, etc.
I've added 2-3 wireframes showing different options of selection i.e, Selection on long tap and checkbox
I wanted to know which option would be preferable.

![22](https://user-images.githubusercontent.com/18495162/41819663-ef388366-77e1-11e8-9841-2c144f92ca2a.png)
![33](https://user-images.githubusercontent.com/18495162/41819666-f7bfec72-77e1-11e8-8351-59870e59b58e.png)
![11](https://user-images.githubusercontent.com/18495162/41819668-fda508de-77e1-11e8-831f-8c7cca5124ee.png)

**Comment by lognaturel** [comment]
I would recommend using checkboxes. Long press is hard to discover and may be completely unknown to users who aren't that familiar with Android or smartphones.

Another thing that occurs to me as I Iook at this now is that users have previously expressed confusion at tab interfaces like the delete screen in Collect. I think only including the text description of the tab for the one that's selected is great. You can also explore options like having an exaggeratedly large [active tab indicator](https://material.io/design/components/tabs.html#anatomy) to make it really clear which one is active.

**Comment by lognaturel** [comment]
I also think showing some metadata below the form names such as "Received on <date>" or "Finalized on <date>" will help with that too.

**Comment by yanokwa** [comment]
Hi @lakshyagupta21 I also prefer checkboxes for common actions because they are visible to the user.
