### ISSUE TITLE
Add user documentation

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#47]
A first pass in the README would be great. It should include a few screenshots where helpful but not so many that they're hard to keep up to date.

Some of the information to include:
* Who is it for?
* Typical connection workflows
* Troubleshooting common issues
* Known limitations

**Comment by yanokwa** [comment]
To me, this is the highest priority issue and we should stop bug fixing until we get this written up. I went through the app and tried to get the basic use case of sending a form from one device to another and I was not successful. I think if @lakshyagupta21 took a day or two to do this, he'd also identify where the gaps in functionality are.

**Comment by yanokwa** [comment]
And I understand that not everything works, but for us to evaluate what is missing vs a bug, we need to know the path that @lakshyagupta21 and @shobhitagarwal1612 take through the app.

**Comment by lognaturel** [comment]
Hmm, not sure why I also filed #78! Closing in favor of that one.
