### ISSUE TITLE
Allow sending of a blank form and media

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#49]

**Comment by lognaturel** [comment]
Currently these are sent along with a filled form, right? So maybe it's just a matter of making that clear to the user? Though I do think there are cases where users will want to send just the blank form and not a filled one (when setting up a campaign for example).

This could be done as add-on work after GSoC but I want to make sure we have an issue to track it!

**Comment by lakshyagupta21** [comment]
> Currently these are sent along with a filled form, right?

Yes, they are sent if it's not present on receiver's device.

**Comment by lognaturel** [comment]
Awesome. So this ties back in to what @yanokwa has said at https://github.com/opendatakit/share/issues/47#issuecomment-406676885 -- getting a first pass at user documentation would really help clarify what a user should expect at each point and will make it easier to see what functionality is there but might benefit from more clarification and what functionality needs to be tracked by new issues.
