### ISSUE TITLE
SQLiteConnection leaked

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#66]
On Android 4.1.1 and master, I get a constant stream of the following error in logcat:

`W/SQLiteConnectionPool(12326): A SQLiteConnection object for database '/storage/sdcard0/odk/metadata/forms.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.`

**Comment by lakshyagupta21** [comment]
Fixed in #67. So closing this issue.
