### ISSUE TITLE
Add graphics to Statistics screen

### ISSUE THREAD

**Issue by lakshyagupta21** [opendatakit/share#69]
Statistics screen can be made more interactive by displaying some charts or graphs 

@shobhitagarwal1612  suggested a library [https://github.com/PhilJay/MPAndroidChart](https://github.com/PhilJay/MPAndroidChart) in PR #64  to add rich graphics.

**Comment by DreamyPhobic** [comment]
Can I work on this issue?  I think a bar graph will be fine for these stats.

**Comment by DreamyPhobic** [comment]
There is only one type of information, i.e, their respective count. So I think bar graph will be good enough to provide a comparison b/w their count. Check below screenshot of the graph. Is it fine?
![screenshot_2018-10-02-02-21-22-641_org odk share 1](https://user-images.githubusercontent.com/33078171/46315092-14654380-c5ea-11e8-81ea-a456067f394b.png)

(Just for showing graph I have taken dummy values.)

**Comment by shobhitagarwal1612** [comment]
Looks really good! Now that the graph is there, I don't think we need the three texts in the bottom for the count anymore.
