### ISSUE TITLE
Provide some kind of form status summary on landing screen

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/share#71]
Currently, there's no way to tell which forms need to be reviewed, which have been received, etc. A small summary either in the summary text or on the right side would help a user figure out which forms are worth clicking on.

**Comment by lakshyagupta21** [comment]
What information can be added? Need some feedback this.

![status](https://user-images.githubusercontent.com/18495162/43369204-68c832f6-9387-11e8-8e27-08f2b24c6a0f.png)

**Comment by lognaturel** [comment]
Thank looks great to me!
