### ISSUE TITLE
(Suggestion) Show an empty view when there are no Filled Forms/Blank Forms

### ISSUE THREAD

**Issue by iadeelzafar** [opendatakit/share#99]
Currently it shows nothing when there are no Filled forms/Blank forms.

![screenshot_11](https://user-images.githubusercontent.com/36811908/52124555-62975b80-264b-11e9-8812-b9c0b6591a07.png)

An empty view will make it more decent.

For example:
This is just an example. I'll make a decent one.

<img src="https://user-images.githubusercontent.com/36811908/52124584-7a6edf80-264b-11e9-816b-30aa4e5de1f5.png" height="550" width="329" >

**I'd love to work on this. Just let me know if I can start working on this.**

**Comment by iadeelzafar** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
Nice idea!
